import numpy as np
a = np.array([1,2,3],dtype=np.int32)
print(a.dtype)
b = np.array([1,2,3])
print(b.dtype)
zero = np.zeros((2,3))
print(zero)
one = np.ones((3,4))
print(one)
empty = np.empty((3,2))
print(empty)
e = np.arange(10)
print(e)
f = np.arange(4,12) 
print(f)
g = np.arange(1,20,3)
h = np.arange(8).reshape(4,2)
